[phases.setup]
aptPkgs = ["openssl", "ca-certificates"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run db:generate", "npm run build:api"]

[start]
cmd = "node apps/api/dist/main"
