[phases.setup]
aptPkgs = ["curl"]

[phases.install]
cmds = ["cd apps/web && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd apps/web && npm run build"]

[start]
cmd = "cd apps/web && node .next/standalone/apps/web/server.js"

[variables]
NODE_ENV = "production"
PORT = "3000"
