[phases.setup]
aptPkgs = ["openssl", "ca-certificates"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = [
  "npm run db:generate",
  "npm run build:api",
  "ls -la apps/api/dist || echo 'dist folder not found!'"
]

[start]
cmd = "node apps/api/dist/main"
